<link rel="alternate" hreflang="en" href="/">
<link rel="alternate" hreflang="ja" href="/index-jp.html">
<link rel="alternate" hreflang="es" href="/index-es.html">
<link rel="alternate" hreflang="es-BR" href="/index-br.html">
<link rel="alternate" hreflang="ko" href="/index-kr.html">
<link rel="alternate" hreflang="vi" href="/index-vi.html">
<link rel="alternate" hreflang="zh-cn" href="/index-zh-cn.html">
<link rel="alternate" hreflang="zh-tw" href="/index-zh-tw.html">
<link rel="alternate" hreflang="fa" href="http://msud.ir/nbpersian/online/">
<link rel="alternate" hreflang="ru" href="http://www.nodebeginner.ru">
