export const EVENT_SESSION_TOKEN_FETCHING_STARTED = "EVENT_SESSION_TOKEN_FETCHING_STARTED";
export const EVENT_SESSION_TOKEN_FETCHING_SUCCEEDED = "EVENT_SESSION_TOKEN_FETCHING_SUCCEEDED";
export const EVENT_SESSION_TOKEN_FETCHING_FAILED = "EVENT_SESSION_TOKEN_FETCHING_FAILED";
export const EVENT_SESSION_TOKEN_FETCHING_ERRORED = "EVENT_SESSION_TOKEN_FETCHING_ERRORED";

export const EVENT_ENTITY_EVENTS_FETCHING_STARTED = "EVENT_ENTITY_EVENTS_FETCHING_STARTED";
export const EVENT_ENTITY_EVENTS_FETCHING_SUCCEEDED = "EVENT_ENTITY_EVENTS_FETCHING_SUCCEEDED";
export const EVENT_ENTITY_EVENTS_FETCHING_ERRORED = "EVENT_ENTITY_EVENTS_FETCHING_ERRORED";

export const EVENT_ENTITY_EVENTS_PUSHING_STARTED = "EVENT_ENTITY_EVENTS_PUSHING_STARTED";
export const EVENT_ENTITY_EVENTS_PUSHING_SUCCEEDED = "EVENT_ENTITY_EVENTS_PUSHING_SUCCEEDED";
export const EVENT_ENTITY_EVENTS_PUSHING_ERRORED = "EVENT_ENTITY_EVENTS_PUSHING_ERRORED";


export const startedFetchingSessionTokenEvent = () => ({ type: EVENT_SESSION_TOKEN_FETCHING_STARTED });
export const succeededFetchingSessionTokenEvent = () => ({ type: EVENT_SESSION_TOKEN_FETCHING_SUCCEEDED });
export const failedFetchingSessionTokenEvent = () => ({ type: EVENT_SESSION_TOKEN_FETCHING_FAILED });
export const erroredFetchingSessionTokenEvent = (error) => ({ type: EVENT_SESSION_TOKEN_FETCHING_ERRORED, error: error });

export const startedFetchingEntityEventsEvent = () => ({ type: EVENT_ENTITY_EVENTS_FETCHING_STARTED });
export const succeededFetchingEntityEventsEvent = (json) => ({ type: EVENT_ENTITY_EVENTS_FETCHING_SUCCEEDED, json: json });

export const startedSyncingEntityEventsEvent = () => ({ type: EVENT_ENTITY_EVENTS_PUSHING_STARTED });
export const succeededSyncingEntityEventsEvent = (entityName) => ({ type: EVENT_ENTITY_EVENTS_PUSHING_SUCCEEDED, entityName: entityName });
